### ISSUE TITLE
Unclear usage

### ISSUE THREAD

**Issue by JonathanWilbur** [YuryStrozhevsky/ASN1-2008-free-test-suite#1]
I appreciate the work you've done, but it's not really clear how I use this test suite. There appears to be two different groups of tests in the `suite` directory: ones that start with `encoded_tc` and others that start with just `tc`. They differ from each other slightly. From which of these do I refer to the PDF for answers, and from which do I refer to the XML decodings for answers?

**Comment by YuryStrozhevsky** [comment]
@JonathanWilbur In fact I put "encoded_tc" and "*.xml" files only for example of expected outcome. So, here is a "transformation chain":
```
tc -> xml -> encoded_tc
```

So, the "tc" files are initial files for the test suite. The XML files are producing as a result of parsing "tc" files. The "encoded_tc" are files producing as a result of encoding of XML files.

Hope it helps.

**Comment by JonathanWilbur** [comment]
That does help! Thank you! Closing this issue.
